FROM node:12-alpine as staticbuilder
ADD --chown=node:node . /builder/
WORKDIR /builder
RUN yarn && yarn cache clean --force
RUN REACT_APP_DISABLE_SENTRY=1 yarn build

FROM nginx:stable
EXPOSE 8000
COPY --from=staticbuilder ./builder/build /usr/share/nginx/html
COPY --from=staticbuilder ./builder/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html

# Copy default environment config and setup script
# Copy package.json so env.sh can read it
COPY ./scripts/env.sh /opt/env.sh
COPY .env /opt/.env
COPY package.json /opt/package.json
RUN chmod +x /opt/env.sh

ENV REACT_APP_DISABLE_SENTRY=1

CMD ["/bin/bash", "-c", "/opt/env.sh /opt /usr/share/nginx/html && nginx -g \"daemon off;\""]
