FROM node:12-alpine as staticbuilder
ADD --chown=node:node . /builder/
WORKDIR /builder
RUN yarn && yarn cache clean --force
RUN yarn build

FROM nginx:alpine
EXPOSE 8000
COPY --from=staticbuilder ./builder/build /usr/share/nginx/html
COPY --from=staticbuilder ./builder/nginx/nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
CMD ["/bin/bash", "-c", "nginx -g \"daemon off;\""]