import { HankeData } from '../../domain/types/hanke';

export const projectsData: HankeData[] = [
  {
    id: 7,
    hankeTunnus: 'SMTGEN2_7',
    onYKTHanke: false,
    nimi: 'Testihanke',
    kuvaus: 'Testihanke',
    alkuPvm: '2021-01-18T00:00:00Z',
    loppuPvm: '2023-01-21T00:00:00Z',
    vaihe: 'SUUNNITTELU',
    suunnitteluVaihe: 'KATUSUUNNITTELU_TAI_ALUEVARAUS',
    version: 0,
    createdBy: '1',
    createdAt: '2021-01-18T12:50:07.330207Z',
    modifiedBy: null,
    modifiedAt: null,
    saveType: 'DRAFT',
    omistajat: [],
    arvioijat: [],
    toteuttajat: [],
    tyomaaKatuosoite: null,
    tyomaaTyyppi: [],
    tyomaaKoko: null,
    haittaAlkuPvm: null,
    haittaLoppuPvm: null,
    kaistaHaitta: null,
    kaistaPituusHaitta: null,
    meluHaitta: null,
    polyHaitta: null,
    tarinaHaitta: null,
    geometriat: {
      id: 2,
      hankeId: 7,
      featureCollection: {
        type: 'FeatureCollection',
        crs: {
          type: 'name',
          properties: {
            name: 'urn:ogc:def:crs:EPSG::3879',
          },
        },
        features: [],
      },
      version: 10,
    },
  },
  {
    id: 11,
    hankeTunnus: 'SMTGEN2_11',
    onYKTHanke: false,
    nimi: 'Testihanke geometrioilla',
    kuvaus: 'Testihankkeen kuvaus',
    alkuPvm: '2021-01-20:00:00Z',
    loppuPvm: '2021-02-01T00:00:00Z',
    vaihe: 'OHJELMOINTI',
    suunnitteluVaihe: null,
    version: 0,
    createdBy: '1',
    createdAt: '2021-01-22T12:16:03.960566Z',
    modifiedBy: null,
    modifiedAt: null,
    saveType: 'DRAFT',
    omistajat: [],
    arvioijat: [],
    toteuttajat: [],
    tyomaaKatuosoite: null,
    tyomaaTyyppi: [],
    tyomaaKoko: null,
    haittaAlkuPvm: null,
    haittaLoppuPvm: null,
    kaistaHaitta: null,
    kaistaPituusHaitta: null,
    meluHaitta: null,
    polyHaitta: null,
    tarinaHaitta: null,
    geometriat: {
      id: 4,
      hankeId: 11,
      featureCollection: {
        type: 'FeatureCollection',
        crs: {
          type: 'name',
          properties: {
            name: 'urn:ogc:def:crs:EPSG::3879',
          },
        },
        features: [
          {
            type: 'Feature',
            properties: null,
            geometry: {
              type: 'Polygon',
              crs: {
                type: 'name',
                properties: {
                  name: 'EPSG:3879',
                },
              },
              coordinates: [
                [
                  [25496691.4, 6673034.35],
                  [25496832.14, 6673044.77],
                  [25496824.14, 6673083.92],
                  [25496679.62, 6673072.23],
                  [25496691.4, 6673034.35],
                ],
              ],
            },
          },
        ],
      },
      version: 0,
    },
  },
  {
    id: 33,
    hankeTunnus: 'SMTGEN2_33',
    onYKTHanke: false,
    nimi: 'Testihanke',
    kuvaus: 'Testihankkeen kuvaus',
    alkuPvm: '2021-02-05T00:00:00Z',
    loppuPvm: '2021-02-14T00:00:00Z',
    vaihe: 'OHJELMOINTI',
    suunnitteluVaihe: null,
    version: 2,
    createdBy: '1',
    createdAt: '2021-02-05T07:29:01.922149Z',
    modifiedBy: '1',
    modifiedAt: '2021-02-05T07:29:14.521696Z',
    saveType: 'DRAFT',
    omistajat: [],
    arvioijat: [],
    toteuttajat: [],
    tyomaaKatuosoite: 'asd',
    tyomaaTyyppi: [],
    tyomaaKoko: null,
    haittaAlkuPvm: null,
    haittaLoppuPvm: null,
    kaistaHaitta: null,
    kaistaPituusHaitta: null,
    meluHaitta: null,
    polyHaitta: null,
    tarinaHaitta: null,
    geometriat: {
      id: 9,
      hankeId: 33,
      featureCollection: {
        type: 'FeatureCollection',
        crs: {
          type: 'name',
          properties: {
            name: 'urn:ogc:def:crs:EPSG::3879',
          },
        },
        features: [
          {
            type: 'Feature',
            properties: null,
            geometry: {
              type: 'Polygon',
              crs: {
                type: 'name',
                properties: {
                  name: 'EPSG:3879',
                },
              },
              coordinates: [
                [
                  [25496723.56, 6672840.59],
                  [25496598.88, 6673013.14],
                  [25496569.96, 6672993.53],
                  [25496692.92, 6672823.94],
                  [25496723.56, 6672840.59],
                ],
              ],
            },
          },
        ],
      },
      version: 1,
    },
  },
];
