import { ApplicationType } from '../../domain/application/types/application';

export enum ROUTES {
  HANKEPORTFOLIO = 'HANKEPORTFOLIO',
  HANKE = 'HANKE',
  HOME = 'HOME',
  PUBLIC_HANKKEET = 'PUBLIC_HANKKEET',
  PUBLIC_HANKKEET_MAP = 'PUBLIC_HANKKEET_MAP',
  PUBLIC_HANKKEET_LIST = 'PUBLIC_HANKKEET_LIST',
  EDIT_HANKE = 'EDIT_HANKE',
  ACCESS_RIGHTS = 'ACCESS_RIGHTS',
  EDIT_USER = 'EDIT_USER',
  FULL_PAGE_MAP = 'FULL_PAGE_MAP',
  HAKEMUS = 'HAKEMUS',
  JOHTOSELVITYSHAKEMUS = 'JOHTOSELVITYSHAKEMUS',
  EDIT_JOHTOSELVITYSHAKEMUS = 'EDIT_JOHTOSELVITYSHAKEMUS',
  EDIT_JOHTOSELVITYSTAYDENNYS = 'EDIT_JOHTOSELVITYSTAYDENNYS',
  KAIVUILMOITUSHAKEMUS = 'KAIVUILMOITUSHAKEMUS',
  EDIT_KAIVUILMOITUSHAKEMUS = 'EDIT_KAIVUILMOITUSHAKEMUS',
  EDIT_KAIVUILMOITUSTAYDENNYS = 'EDIT_KAIVUILMOITUSTAYDENNYS',
  HAITATON_INFO = 'HAITATON_INFO',
  ACCESSIBILITY = 'ACCESSIBILITY',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  REFERENCES = 'REFERENCES',
  MANUAL = 'MANUAL',
  WORKINSTRUCTIONS = 'WORKINSTRUCTIONS',
  CARDS_INDEX = 'CARDS_INDEX',
  CARD_1_BASIC = 'CARD_1_BASIC',
  CARD_1_ADDITIONAL = 'CARD_1_ADDITIONAL',
  CARD_2_BASIC = 'CARD_2_BASIC',
  CARD_2_ADDITIONAL = 'CARD_2_ADDITIONAL',
  CARD_3_BASIC = 'CARD_3_BASIC',
  CARD_3_ADDITIONAL = 'CARD_3_ADDITIONAL',
  CARD_4_BASIC = 'CARD_4_BASIC',
  CARD_4_ADDITIONAL = 'CARD_4_ADDITIONAL',
  CARD_5_BASIC = 'CARD_5_BASIC',
  CARD_5_ADDITIONAL = 'CARD_5_ADDITIONAL',
  CARD_6_BASIC = 'CARD_6_BASIC',
  CARD_6_ADDITIONAL = 'CARD_6_ADDITIONAL',
  CARD_7_BASIC = 'CARD_7_BASIC',
  CARD_7_ADDITIONAL = 'CARD_7_ADDITIONAL',
  CARD_8_BASIC = 'CARD_8_BASIC',
  CARD_8_ADDITIONAL = 'CARD_8_ADDITIONAL',
  CARD_9_BASIC = 'CARD_9_BASIC',
  CARD_9_ADDITIONAL = 'CARD_9_ADDITIONAL',
  CARD_10_BASIC = 'CARD_10_BASIC',
  CARD_10_ADDITIONAL = 'CARD_10_ADDITIONAL',
}

export type Route = keyof typeof ROUTES;

export type RouteData = {
  label: string;
  path: string;
  meta: {
    title: string;
  };
};

export type RouteMap = Record<keyof typeof ROUTES, RouteData>;

export const HAKEMUS_ROUTES: Record<ApplicationType, ROUTES> = {
  CABLE_REPORT: ROUTES.EDIT_JOHTOSELVITYSHAKEMUS,
  EXCAVATION_NOTIFICATION: ROUTES.EDIT_KAIVUILMOITUSHAKEMUS,
};

export const HAKEMUS_TAYDENNYS_ROUTES: Record<ApplicationType, ROUTES> = {
  CABLE_REPORT: ROUTES.EDIT_JOHTOSELVITYSTAYDENNYS,
  EXCAVATION_NOTIFICATION: ROUTES.EDIT_KAIVUILMOITUSTAYDENNYS,
};
