name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - run: yarn type-check
      - name: Tar build files
        run: tar -cvf build.tar build
      - name: Upload application build files for Docker build job
        uses: actions/upload-artifact@v2
        with:
          name: haitaton-ui-build
          path: build.tar
          retention-days: 1
  e2e:
    name: Browser tests
    needs: build
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download application build files
        uses: actions/download-artifact@v2
        with:
          name: haitaton-ui-build
      - name: Untar build files
        run: tar -xvf build.tar
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run serve
          wait-on: 'http://localhost:3001'
  docker_build_and_push:
    name: Push Docker image to GitHub Packages
    needs: [build, e2e]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download application build files
        uses: actions/download-artifact@v2
        with:
          name: haitaton-ui-build
      - name: Untar build files
        run: tar -xvf build.tar
      - name: List files after checkout
        shell: bash
        run: |
          ls -ltra
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to OpenShift Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHSA_USERNAME }}
          password: ${{ secrets.RHSA_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/haitaton/ui:latest
            ghcr.io/city-of-helsinki/haitaton/ui:dev
  temp_test_deploy:
    name: Trigger deployment to temporary test environment at haitaton.kaupunkiymparisto.fi
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEPLOY_REPO_ACCESS_TOKEN }}
          repository: City-of-Helsinki/haitaton-deploy
          event-type: haitaton-ui
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
