name: ui-pr

on:
  push:
    branches:
      - 'HAI-**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn type-check
      - name: Tar build files
        run: tar -cvf build.tar build
      - name: Upload application build files for Docker build job
        uses: actions/upload-artifact@v2
        with:
          name: haitaton-ui-build
          path: build.tar
          retention-days: 1
  docker_build_and_push:
    name: Push Docker image to GitHub Packages
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download application build files
        uses: actions/download-artifact@v2
        with:
          name: haitaton-ui-build
      - name: Untar build files
        run: tar -xvf build.tar
      - name: List files after checkout
        shell: bash
        run: |
          ls -ltra
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to OpenShift Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHSA_USERNAME }}
          password: ${{ secrets.RHSA_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/haitaton/ui:latest
            ghcr.io/city-of-helsinki/haitaton/ui:dev
