name: ui-pr

on:
  push:
    branches:
      - 'HAI-**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - run: yarn type-check
      - name: Tar build files
        run: tar -cvf build.tar build
      - name: Upload application build files for Docker build job
        uses: actions/upload-artifact@v2
        with:
          name: haitaton-ui-build
          path: build.tar
          retention-days: 1
