name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn lint
      - run: yarn type-check
      - name: Upload application files for Docker build job
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: actions/upload-artifact@v2
        with:
          name: haitaton-ui-build
          path: build
          retention-days: 1
  e2e:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
  push_to_github_packages:
    name: Push Docker image to GitHub Packages
    needs: [build, e2e]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Download application files
        uses: actions/download-artifact@v2
        with:
          name: haitaton-ui-build
      -
        name: List files after checkout
        shell: bash
        run: |
          ls -ltra
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to OpenShift Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.redhat.io
          username: ${{ secrets.RHSA_USERNAME }}
          password: ${{ secrets.RHSA_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_OWNER }}
          password: ${{ secrets.CR_PAT }}
      -
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/city-of-helsinki/haitaton/haitaton-ui:latest
            ghcr.io/city-of-helsinki/haitaton/haitaton-ui:dev
